name: Flutter Web Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.17.0'
          channel: 'dev'
      - run: flutter --version

      - name: Check out code
        uses: actions/checkout@v3
        
      - name: checkout 
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web
