name: Flutter Web Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web
